% Synthetic mesh fixture: 12 words, grid 15x15, alphabet 8, lengths 3-4, seed 11.
% Generated by benchmarks/gen_mesh_fixture.py 15 12 8 3 4 11 (idea I4).
%% Short interlocking words read off a witness layout: satisfiable by construction,
%% hard for baseline (small alphabet + shuffled order), tractable for MRV.
clues([
       ['EEE'],
       ['HHDC'],
       ['GDBG'],
       ['FHFE'],
       ['GBBA'],
       ['CHAG'],
       ['BAE'],
       ['HDD'],
       ['DGBC'],
       ['FCGE'],
       ['CCC'],
       ['GFEC']
      ]).
