% Synthetic mesh fixture: 25 words, grid 21x21, alphabet 7, lengths 3-4, seed 11.
% Generated by benchmarks/gen_mesh_fixture.py 21 25 7 3 4 11 (idea I4).
%% Short interlocking words read off a witness layout: satisfiable by construction,
%% hard for baseline (small alphabet + shuffled order), tractable for MRV.
clues([
       ['BGC'],
       ['FDA'],
       ['ACA'],
       ['BEAA'],
       ['GEAA'],
       ['DAD'],
       ['AEA'],
       ['DACB'],
       ['FAD'],
       ['FCGC'],
       ['EDC'],
       ['AEGE'],
       ['AAAB'],
       ['GBB'],
       ['GEGG'],
       ['AAF'],
       ['GGB'],
       ['CCGA'],
       ['GGCC'],
       ['AACD'],
       ['DAAB'],
       ['GGE'],
       ['CFA'],
       ['GDEA'],
       ['CAGE']
      ]).
