% Synthetic mesh fixture: 16 words, grid 9x9, alphabet 5, lengths 3-4, seed 11.
% Generated by benchmarks/gen_mesh_fixture.py 9 16 5 3 4 11 (idea I4).
%% Short interlocking words read off a witness layout: satisfiable by construction,
%% hard for baseline (small alphabet + shuffled order), tractable for MRV.
clues([
       ['DBB'],
       ['AAD'],
       ['AABC'],
       ['CBEB'],
       ['DBA'],
       ['EAD'],
       ['ADC'],
       ['DADC'],
       ['BDDA'],
       ['EAB'],
       ['BDEA'],
       ['DCB'],
       ['ECE'],
       ['EDDE'],
       ['AEAA'],
       ['BCB']
      ]).
