% Synthetic mesh fixture: 28 words, grid 15x15, alphabet 6, lengths 3-4, seed 11.
% Generated by benchmarks/gen_mesh_fixture.py 15 28 6 3 4 11 (idea I4).
%% Short interlocking words read off a witness layout: satisfiable by construction,
%% hard for baseline (small alphabet + shuffled order), tractable for MRV.
clues([
       ['AFBF'],
       ['EAB'],
       ['DBED'],
       ['ABCB'],
       ['CDF'],
       ['ACA'],
       ['ABFA'],
       ['FCC'],
       ['DEAA'],
       ['DFAD'],
       ['BBEF'],
       ['FCF'],
       ['AFCC'],
       ['EFAF'],
       ['CCD'],
       ['BFF'],
       ['EFD'],
       ['EADF'],
       ['EDDE'],
       ['DED'],
       ['DACA'],
       ['CBED'],
       ['FAFB'],
       ['CADF'],
       ['EAA'],
       ['CEF'],
       ['BCD'],
       ['DEF']
      ]).
