% Synthetic mesh fixture: 22 words, grid 11x11, alphabet 5, lengths 3-4, seed 7.
% Generated by benchmarks/gen_mesh_fixture.py 11 22 5 3 4 7 (idea I4).
%% Short interlocking words read off a witness layout: satisfiable by construction,
%% hard for baseline (small alphabet + shuffled order), tractable for MRV.
clues([
       ['BCB'],
       ['DBA'],
       ['AAB'],
       ['AEB'],
       ['EEDD'],
       ['CBA'],
       ['BAEB'],
       ['EDD'],
       ['DDD'],
       ['BDBA'],
       ['CDCE'],
       ['EEC'],
       ['AACD'],
       ['BED'],
       ['DBEE'],
       ['BCA'],
       ['AAE'],
       ['DDB'],
       ['DADA'],
       ['BDAA'],
       ['CEB'],
       ['DBCC']
      ]).
