% Real-word product fixture: 12 words, grid 13x13, lengths 4-9 + anchor 11, seed 11.
% Generated by benchmarks/gen_real_fixture.py 13 12 fixtures/dict/enable1.txt 4 9 11 (rework plan par.6/par.9).
%% ENABLE dictionary words planted on a legal witness layout: satisfiable and
%% reachable by construction; a realistic arrange input at a blocked daily size.
clues([
       ['SOZINS'],
       ['USED'],
       ['LUGE'],
       ['AGRAFFE'],
       ['ESCUAGES'],
       ['ECHE'],
       ['EFFACING'],
       ['INVOLUTE'],
       ['GRUDGE'],
       ['KILLING'],
       ['HAZIER'],
       ['KINKINESSES']
      ]).
