% Real-word product fixture: 18 words, grid 15x15, lengths 4-9 + anchor 13, seed 11.
% Generated by benchmarks/gen_real_fixture.py 15 18 fixtures/dict/enable1.txt 4 9 11 (rework plan par.6/par.9).
%% ENABLE dictionary words planted on a legal witness layout: satisfiable and
%% reachable by construction; a realistic arrange input at a blocked daily size.
clues([
       ['BRIO'],
       ['WORT'],
       ['BUTS'],
       ['POSSE'],
       ['YEALINGS'],
       ['JATO'],
       ['KATZENJAMMERS'],
       ['INFO'],
       ['RELIER'],
       ['ARGONAUT'],
       ['SUBMISS'],
       ['DECODE'],
       ['FEASE'],
       ['MUCOUS'],
       ['MYASES'],
       ['UMBONES'],
       ['ETUIS'],
       ['IMBED']
      ]).
