// golden_type_check.mjs - the golden-satisfies-type drift lock (DEC-5).
//
// The SDK's types are hand-written (wasm/sdk/crosswordsmith.d.ts); nothing
// else would notice if the emitter and the types drifted apart. This lock
// embeds the committed golden fixtures as TypeScript object literals annotated
// `: Layout` — contextual typing then enforces the full structural contract
// (missing fields, wrong scalar types, unions like direction/"across"|"down",
// EXCESS properties the type doesn't know about) — and runs tsc --noEmit.
// A plain JSON import would not work: imported JSON widens literals (e.g.
// "across" to string), defeating the union checks.
//
// Prereq: ( cd wasm/test && npm install )        # typescript devDependency
// Run:    node wasm/test/golden_type_check.mjs   (exit 0 = goldens satisfy Layout)

import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const goldens = [
  'tests/golden/arrange_bundled_17_fixed.json',
  'tests/golden/arrange_toc_demo_max.json',
];

let src = `// GENERATED by golden_type_check.mjs — do not edit, do not commit.
import type { Layout } from "../sdk/crosswordsmith";
`;
goldens.forEach((rel, i) => {
  const parsed = JSON.parse(readFileSync(join(here, '../..', rel), 'utf8'));
  src += `\n// ${rel}\nconst golden${i}: Layout = ${JSON.stringify(parsed, null, 2)};\n`;
  src += `void golden${i};\n`;
});
src += `export {};\n`;

const generated = join(here, 'golden_type_check.generated.ts');
writeFileSync(generated, src);

try {
  execFileSync('npx', ['--no-install', 'tsc', '--noEmit', '--strict', generated],
               { cwd: here, stdio: 'inherit' });
  console.log(`golden-type-check OK (${goldens.length} goldens satisfy Layout)`);
} catch {
  console.error('golden-type-check FAILED: a committed golden no longer satisfies the hand-written Layout type');
  process.exit(1);
} finally {
  rmSync(generated, { force: true });
}
